### ISSUE TITLE
Re-use Builder instance

### ISSUE THREAD

**Issue by j-mendez** [thefux/storage-rs#6]
Hi, thank you for the crate. It would be ideal to be able to re-use the Builder instance instead of having to clone `url`, `headers`, and `client` on each call. If headers and url can move to an Arc it would be ok instead of the architecture removing `body: Option<BodyType>` from the Builder struct. Performing constant clones adds up when processing a lot of items at once.

**Comment by thefux** [comment]
Hi, that was kind of intentional at the beginning, was aware of the issue but assumed :) no one will used it the way you describe, it is for sure something that needs to be done, but I'm not sure when I could takle the issue, will try though asap.

**Comment by j-mendez** [comment]
@thefux nice entry into the changes. The arc is the main thing needed. It would be better to use a self struct inner value to mutate and use the arc at the end with a build method to avoid locking threads.

**Comment by thefux** [comment]
@j-mendez I'm not sure what do u mean, maybe some code ?

**Comment by j-mendez** [comment]
@thefux np.

If we build the client through a builder method ClientBuilder is returned once ready. This helps avoiding messy locking that is not needed for this situation ex:

```rs
        self.headers
            .lock()
            .unwrap()
```

The `build` function needs to be ran with the method and body. `builder.build(method, body, headers)`

We would also need to change the `self.body` and `self.method` as those would be applied on the function call and not stored for the struct.

Builder example struct would only contain two values. Really the URL if done right does not need to be stored and just the parsing done for the method urls on build.

```rust
pub struct Builder {
    pub url: Url,
    pub request: RequestBuilder,
}
```

`Executor` could efficiently contain the method and the body that way the clones are not needed and the main client is re-used.

Instead of using the call to `Storage.from` we would return the `Builder` instance.

**Comment by j-mendez** [comment]
I think it would be better to `yank` 0.2.0, since cloning is more ideal than locking threads for the concurrency hit. I can take a look this weekend more for the changes.

**Comment by thefux** [comment]
thanks, will see what I can do this week..

> I think it would be better to yank 0.2.0, since cloning is more ideal than locking threads for the concurrency hit. I can take a look this weekend more for the changes.

👍
